name:                QDHXB
version:             0.0.0.1
github:              "jphmrst/QDHXB"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jphmrst/QDHXB#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- extra
- mtl
- template-haskell
- time
- transformers >=0.5 && < 0.6
- symbol
- xml
- free          # For DebuglnT
- resourcet     # For DebuglnT
- STMonadTrans  # For DebuglnT

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

# - -ddump-splices

library:
  source-dirs: src
  ghc-options:
  - -Wmissing-export-lists
  - -Wmissing-home-modules

executables:
  QDHXB-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QDHXB

tests:
  QDHXB-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QDHXB
    - TLT  >= 0.5.0.0
