{-# LANGUAGE TemplateHaskell #-}

-- | Quick-and-Dirty Haskell/XSD bindings
module QDHXB (
  -- * Invoking QDHXB
  qdhxb, qdhxb',

  -- * Options
  --
  -- | These options for the `qdhxb` function are re-exported from the
  -- @QDHXB.Options@ module.
  QDHXBOption,
  -- ** Structure of renamed types
  useNewType, noUseNewType,

  -- * Other re-exported utilities
  --
  -- | These values are used in the code generated by `qdhxb` and
  -- `qdhxb'`, and therefore are re-exported here for convenience.
  Content,
  ZeroOneMany(Zero, One, Many),
  pullContentFrom, zomToList, loadElement
  ) where

import Language.Haskell.TH (Q, Dec)
-- import System.Directory
import System.IO
import Control.Monad.IO.Class
import Text.XML.Light.Input (parseXML)
import Text.XML.Light.Types (Content(Elem), Element(Element), QName(QName))
import QDHXB.Internal.Generate
import QDHXB.Internal.Input
import QDHXB.Internal.Flatten
import QDHXB.Internal.XSDQ (XSDQ, runXSDQ)
import QDHXB.Options
import QDHXB.XMLLight

-- | Load the given XSD files, translating each into Haskell
-- declarations.
qdhxb :: QDHXBOption -> [String] -> Q [Dec]
qdhxb _ xsds = do
  -- liftIO (getCurrentDirectory >>= putStrLn . show)
  runXSDQ $ fmap concat $ mapM loadFile xsds

-- | Load and translate the given XSD files with the default options.
qdhxb' :: [String] -> Q [Dec]
qdhxb' = qdhxb id

loadFile :: String -> XSDQ [Dec]
loadFile xsdFile = do
  xsd <- liftIO $ readFile' xsdFile
  let xml = parseXML xsd
  xmlToDecs $ filter isElem xml

-- | Convert XML `Content` into a quotation monad returning top-level
-- Haskell declarations.
xmlToDecs :: [Content] -> XSDQ [Dec]
xmlToDecs ((Elem (Element (QName "?xml" _ _) _ _ _)) : ds) = case ds of
  (Elem (Element (QName "schema" _ _) _ forms _) : []) -> do
    schemaReps <- encodeSchemaItems forms
    -- liftIO $ putStrLn $ "====== REPS\n" ++ show schemaReps ++ "\n======\n"
    ir <- flattenSchemaItems schemaReps
    -- liftIO $ putStrLn $ "====== IR\n" ++ show ir ++ "\n======\n"
    decls <- xsdDeclsToHaskell ir
    return decls
  _ -> error "Expected top-level <schema> element"
xmlToDecs _ = error "Missing <?xml> element"
